- name: Ｊ：ＣＯＭチャンネル
  type: GR
  channel: '13'
  isDisabled: false
- name: Ｊ：ＣＯＭテレビ
  type: GR
  channel: '17'
  isDisabled: false
- name: ｔｖｋ
  type: GR
  channel: '18'
  isDisabled: false
- name: ＴＯＫＹＯ　ＭＸ
  type: GR
  channel: '20'
  isDisabled: false
- name: フジテレビ
  type: GR
  channel: '21'
  isDisabled: false
- name: ＴＢＳ
  type: GR
  channel: '22'
  isDisabled: false
- name: テレビ東京
  type: GR
  channel: '23'
  isDisabled: false
- name: テレビ朝日
  type: GR
  channel: '24'
  isDisabled: false
- name: 日テレ
  type: GR
  channel: '25'
  isDisabled: false
- name: ＮＨＫＥテレ
  type: GR
  channel: '26'
  isDisabled: false
- name: ＮＨＫ総合
  type: GR
  channel: '27'
  isDisabled: false
- name: テレ玉
  type: GR
  channel: '32'
  isDisabled: false
